version: "3"

services: 
  reverse-proxy:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    container_name: reverse-proxy
  web:
    image: httpd:alpine
    container_name: web

networks:
  default:
    name: webinar-compose