version: '3'

volumes:
  mariadb:
    driver: local

networks:
  db:
    driver: bridge

services:
  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER:  user
      MARIADB_PASSWORD: password
    expose:
      - "40000"
    ports:
      - "40000:3306"
    volumes:
      - "./mariadb-dump:/docker-entrypoint-initdb.d"
    networks:
      db:

  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - "40001"
    ports:
      - "40001:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306 
    networks:
      db:       
    
  www:
    image: php:8.1-apache-buster
    volumes: 
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443