version: "3.1"
services:
    db:
        container_name: mysql8
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_db
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
        ports:
            - 3306:3306

        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    www:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php74
        ports:
            - "8000:80"
        volumes:
            - ./www:/var/www/html
        links:
            - db
        networks:
            - default
volumes:
    persistent:
